### ISSUE TITLE
Still Release 1.0 of the dps8m emulator?

### ISSUE THREAD

**Issue by tsimblist** [RattyDAVE/alpine-multics#1]
As best as I can understand from the Dockerfile, you are still at Release 1.0 of the dps8m emulator.

Release 2.0 has been available for a while now.  What are your plans for upgrading to 2.0?

**Comment by RattyDAVE** [comment]
Oh I was unaware..... Let me look... wont take long..

**Comment by RattyDAVE** [comment]
The beta tag has v2.0 .. not working 100% as I like.. Ok for testing.

**Comment by RattyDAVE** [comment]
Bad news ... v2.0 has to many issues.
Good news ... The latest from version DPS8/M simulator V4.0-0 Beta works really well.

To use... 

```
docker run -d --name multics \
           -p 6180:6180 \
           rattydave/alpine-multics:beta
```
