### ISSUE TITLE
Does this result in a usable system?

### ISSUE THREAD

**Issue by lojikil** [RattyDAVE/alpine-multics#2]
I apologize if I missed something obvious, but I've not been able to successfully add a user to the system, and it seems like the underlying Multics is in an odd state (perhaps we need to rebuild it?)

I did some digging and found the `new_proj` and `new_user` programs, as well as some EC scripts to support adding users. I also did some digging into Multics sysop guides, and did find `cv_pmf` and the like. However, other programs, such as `register` appear to be missing, at least when I login as the `Repair.SysAdmin` user. I've tried:

-  Adding projects then adding users
-  Adding users then adding them to projects
-  adding users to existing projects, like adding a user to the SysAdmin project

None of which worked; I was able to get it to the point where User Service reports that the user isn't part of a project or that the project doesn't exist, but not really any further. Am I missing something obvious? 

And also, thank you so much for your work on this!

**Comment by RattyDAVE** [comment]
I am sorry but my knowledge is limited on this. 

https://www.multicians.org/ 

Just for confirmation though I have tried myself and can create a user. But have the same problem with creating a project.

NOTE: a project is the like a group in current *nix/bsd systems.

**Comment by RattyDAVE** [comment]
A bit more playing

`ec master new_proj DaveTest`

**Comment by lojikil** [comment]
AH interesting, I didn't try with `master` in there; I've used Multics and Multics-alike systems before, but never actually attempted to _administer_ one before. That's perfect, let me try that! and thank you!

_edit_ for others that stumble into this:

I have to run `master.ec` in `>udd>SysAdmin>admin` ala `ec >tools>master new_proj &PROJ`, which gets me one step closer.

1. `cwd >udd>SysAdmin>admin`
2. `ec >tools>master new_proj &PROJ` where `&PROJ` is the name

```
login Repair.TestTest
Password:
Another Repair (Repair.TestTest) is now logging in from ASCII terminal "none".
This is your 2nd interactive login instance.
Load control group full. Please try again later.
Please try to login again or type "help" for instructions.
``` 

I'll experiment a bit more here
