### ISSUE TITLE
missing dps8?

### ISSUE THREAD

**Issue by lilyanatia** [RattyDAVE/alpine-multics#3]
when attempting to start the container, I get this error:
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "dps8": executable file not found in $PATH: unknown.
```

there indeed does not seem to be any dps8 in the container:
```
$ docker export multics | tar t | grep dps8 || echo dps8 not found
dps8 not found
```

**Comment by RattyDAVE** [comment]
Ahhhhhh!!!! (Mad Screaming)

I was rebuilding and patching the container over the weekend and I thought I tested all of them before I pushed.

Ill look into it now. 

For now accept my apologies.

**Comment by RattyDAVE** [comment]
Try now. I am using alpine 3.18

**Comment by lilyanatia** [comment]
thanks, looks like it's fixed now
